# Generated by Django 3.0.2 on 2020-02-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_topics',
            name='topics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.topics'),
        ),
        migrations.AddField(
            model_name='topics',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create.courses'),
        ),
    ]
