# Generated by Django 3.0.2 on 2020-02-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20200227_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c_to_t',
            new_name='course_to_topics',
        ),
        migrations.RenameModel(
            old_name='t_to_c',
            new_name='topics_to_subtopics',
        ),
    ]
