# Generated by Django 3.0.3 on 2020-02-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
