# Generated by Django 3.0.3 on 2020-03-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_auto_20200229_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_topics',
            old_name='topics',
            new_name='topic',
        ),
    ]
