# Generated by Django 3.0.3 on 2020-03-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_auto_20200306_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_topics',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sub_topics',
            name='pdf',
        ),
    ]
