# Generated by Django 3.0.4 on 2020-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20200306_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_topics',
            name='sno',
            field=models.PositiveIntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='topics',
            name='sno',
            field=models.PositiveIntegerField(default=0, max_length=20),
        ),
    ]
