# Generated by Django 3.0.4 on 2020-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0010_auto_20200307_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_topics',
            name='sno',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topics',
            name='sno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
