# Generated by Django 3.0.4 on 2020-03-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_auto_20200307_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_topics',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
