# Generated by Django 3.0.2 on 2020-03-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_auto_20200307_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_topics',
            name='pdf',
        ),
    ]
