# Generated by Django 3.0.2 on 2020-03-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0014_remove_sub_topics_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_topics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
