# Generated by Django 3.0.3 on 2020-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0017_auto_20200309_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='sub_topics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
